# Generated by Django 5.0.1 on 2024-03-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='usuario',
        ),
    ]
