# Generated by Django 5.0.1 on 2024-03-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0002_remove_transacao_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="parcela_atual",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="transacao",
            name="parcelas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
