# Generated by Django 5.0.1 on 2024-03-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0003_transacao_parcela_atual_transacao_parcelas"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="total_parcelas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
