# Generated by Django 5.0.1 on 2024-03-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0005_remove_transacao_total_parcelas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.transacao",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Recebido",
        ),
    ]
