# Generated by Django 5.0.1 on 2024-03-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0006_parcela_delete_recebido"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
            ],
        ),
    ]
